// Downloads the two brand webfonts from Google Fonts into public/fonts/ and
// regenerates src/styles/fonts.css to point at the local copies.
//
// WHY self-host:
//  - Performance: the <link> to fonts.googleapis.com was a render-blocking
//    stylesheet on a THIRD origin — DNS + TCP + TLS before the browser even
//    learns which .woff2 files it needs (Lighthouse: "render-blocking requests
//    ~1050 ms"). Locally the @font-face rules ship inside the bundled CSS the
//    browser is already fetching, and the files sit on the same connection.
//  - DSGVO: loading the CSS from Google transmits the visitor's IP address to
//    Google in the US on every page view without consent (LG München I,
//    3 O 17493/20). Self-hosting removes that transfer entirely.
//
// Only the `latin` and `latin-ext` subsets are kept — the site is German, and
// the cyrillic/greek/vietnamese subsets were 30 of the 40 @font-face blocks.
// The weight RANGES (300..600 / 400..700) make Google serve the VARIABLE font,
// so it is one file per subset instead of one per weight.
//
// Run:  node scripts/fetch-fonts.mjs
import { mkdirSync, writeFileSync, statSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const fontDir = path.join(root, "public", "fonts");
mkdirSync(fontDir, { recursive: true });

// Inter is deliberately NOT here. The old Google Fonts <link> requested it in
// four weights, but the app sets font-['Space_Grotesk'] on the root wrapper and
// there is not a single `Inter` reference anywhere in src/ — the browser
// downloaded a whole second family it never painted with.
const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400..700&display=swap";

// A modern desktop UA makes the API answer with woff2 (the smallest format).
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const KEEP = new Set(["latin", "latin-ext"]);

const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();

// Blocks look like:  /* latin */\n@font-face { ... }
const blocks = css
  .split(/\/\*\s*([a-z-]+)\s*\*\//i)
  .slice(1)
  .reduce((acc, part, i, arr) => {
    if (i % 2 === 0) acc.push({ subset: part.trim(), body: (arr[i + 1] || "").trim() });
    return acc;
  }, []);

const out = [];
let total = 0;

for (const { subset, body } of blocks) {
  if (!KEEP.has(subset)) continue;
  const family = /font-family:\s*'([^']+)'/.exec(body)?.[1];
  const url = /url\((https:\/\/[^)]+\.woff2)\)/.exec(body)?.[1];
  if (!family || !url) continue;

  const slug = `${family.toLowerCase().replace(/\s+/g, "-")}-${subset}.woff2`;
  const buf = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
  writeFileSync(path.join(fontDir, slug), buf);
  total += buf.length;
  console.log(`${family} / ${subset}`.padEnd(30), slug.padEnd(34), `${(buf.length / 1024).toFixed(0)} KB`);

  out.push(
    body
      .replace(/url\(https:\/\/[^)]+\.woff2\)/, `url('/fonts/${slug}')`)
      .replace(/^\/\*[^*]*\*\/\s*/, ""),
  );
}

const header = `/* GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.
 *
 * Self-hosted Space Grotesk (variable, latin + latin-ext only).
 * Previously these came from fonts.googleapis.com via a <link> in index.html,
 * which cost a render-blocking third-party round trip AND sent every visitor's
 * IP to Google (DSGVO). Re-run the script to refresh the files.
 */
`;

writeFileSync(path.join(root, "src", "styles", "fonts.css"), header + "\n" + out.join("\n\n") + "\n");
console.log(`\n${out.length} Dateien, ${(total / 1024).toFixed(0)} KB gesamt → public/fonts/`);
console.log(`src/styles/fonts.css neu geschrieben (${(statSync(path.join(root, "src", "styles", "fonts.css")).size / 1024).toFixed(1)} KB)`);
